### PR TITLE
Add babel-cli

### PR DESCRIPTION
**Pull request by rsmylskibc**
- Moved old lib folder to src
- Added build script to babel src and out to lib/alternatives.js
- Added src to npmignore

### CODE REVIEW

**Comment by rsmylskibc** [comment]
Would I need to specify anything in the babel command or .babelrc to ensure it's outputted as es5

**Comment by gurbraj** [comment]
As I've understood it, all of the files are generated from running Babel on the files in source. 

LGTM

**Comment by rsmylskibc** [comment]
The commits got messy.

I ended up moving original `lib` to `src`. Babel now builds src into lib. However, I didn't do these in separate commits, so it's treating lib as being modified, and src as being new, where it should be more, the files in src being untouched but renamed, and then new babel'd files in lib.

Essentially ignore lib, as it's generated code, and not real changes.

@gburtini should I back this all out and try to get my commits down to match my intent?

**Comment by gburtini** [comment]
No, I think the commit history is fine. You can do a squash merge if you want when this merges down to better indicate your intent.

**Comment by gburtini** [comment]
Normally, it would be inappropriate to include babel'd code in the repo. While it will work as you've presented it, I would prefer it if you used a NPM `postinstall-build` hook: https://www.npmjs.com/package/postinstall-build

**Review by gburtini — APPROVED** [review]

**Pull request merged**
